version: 2.1
orbs:
  docker: circleci/docker@2.8.0

jobs:

  deploy-docker-build:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: suculent/mongoose-docker-build
          tag: latest
      - docker/push:
          digest-path: /tmp/digest.txt
          image: suculent/mongoose-docker-build
          tag: latest
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
            docker tag $(</tmp/digest.txt) suculent/mongoose-docker-build:latest

#
# WORKFLOWS
#

workflows:

  build:
    jobs:
      - deploy-docker-build:
          context:
            - dockerhub
          filters:
            branches:
              only: master